


class Human
{
	private int age;
	private String name;
	
	public Human()
	{
		age=12;
		name="John";
	}
	public Human(String name) {
		this.age=age;
		this.name=name;
	}
	public Human(int age, String name)
	{
		this.age=age;
		this.name=name;
	}
	
	
//	public Human()    //default constructor
//	{
//		age=12;
//		name="John";
//		//System.out.println("in constructor");
//	}
//	public Human(int a, String n)  //Parameterized constructor
//	{
//		age=a;
//		name=n;
//	}
	
	public int getAge(){
		return age;
	}
	public void SetAge(int age)
	{
		this.age=age;
	}	
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name=name;
	}
}

public class _08_constructorType {
	public static void main(String[] args) throws ClassNotFoundException
	{
		Human obj=new Human();
//		Human obj1=new Human(18, "Navin");
		System.out.println(obj.getName()+" : "+obj.getAge());
//		System.out.println(obj1.getName()+" : "+obj1.getAge());
		
//		obj.SetAge(30);
//		obj.setName("Reddy");
		

		//System.out.println(obj.getName()+" : "+obj.getAge());
	}
}


/*
- Types of constructors in Java
- What are Parameterized constructors?
- What are default constructors?

A constructor in Java is a special method that is used to initialize objects. 

Parameterized Constructor:-
- A constructor that takes some parameters is known as parameterized constructor.
- The parameterized constructor is used to provide different values to different objects.

Default Constructor:-
- A normal constructor is known as the default constructor.
- If you do not create any constructor, then java creates a default constructor. That constructor will be blank with no parameters.
- The default constructor is used to provide the default values to the object like 0, null, etc., depending on the type.

- The default constructor can change into the parameterized constructor. But Parameterized constructor can’t change into the default constructor.i.e.once a class has a
//                                                                                                            parameterized constructor, it cannot have a default constructor automatically generated by the compiler.
*/